// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOM6NAn5ktzfanooBJJZelEfnY3lZ4WiU',
    appId: '1:75477171815:web:900b4ceab2b8f31d311ec2',
    messagingSenderId: '75477171815',
    projectId: 'derickdev',
    authDomain: 'derickdev.firebaseapp.com',
    databaseURL: 'https://derickdev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'derickdev.appspot.com',
    measurementId: 'G-TGKBC8TEK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc-MVf1arSZDk4th0nc0AWH8t-FjdnzOA',
    appId: '1:75477171815:android:0379266b10c93fc4311ec2',
    messagingSenderId: '75477171815',
    projectId: 'derickdev',
    databaseURL: 'https://derickdev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'derickdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwXe4T-oujzyUF7CvYnnbrpQW3DNvDi_E',
    appId: '1:75477171815:ios:32bc2b94f8f17781311ec2',
    messagingSenderId: '75477171815',
    projectId: 'derickdev',
    databaseURL: 'https://derickdev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'derickdev.appspot.com',
    androidClientId: '75477171815-iqlm1erfof83gta8rgkfisg4rfgn32t4.apps.googleusercontent.com',
    iosClientId: '75477171815-jffnhlglh6rjrteggo677m58sa1boosv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

}